#ifndef WIRECELLUTIL_VERSION
#define WIRECELLUTIL_VERSION

#include "config.h"

namespace WireCell {

     // Note, this is defined in config.h, usually found under the
     // default build/ directory.  It is generated by waf.  See top of
     // wscript file for how.  To make a "clean" version without any
     // git hash fragement, you must build from an pristine git repo
     // that has been checked out on a tag.
     const char* version = WIRECELL_VERSION ;
     
}
#endif

