#+title: 🍮 custard

* Overview

*custard* provides two header-only libraries:

- [[file:custard.hpp]] :: stand-alone, header-only C++ interface to
  reading and writing tar streams via ~std::ostream~ (or derived)

- [[file:boost_custard.hpp]] :: ~boost::iostreams~ input filters ~tar_reader~ and
  output filter ~tar_writer~.  This is header-only and depends on
  ~custard.hpp~

The filters require the user to follow a simple streaming protocol
which serializes to/from the stream, in order:

1. file name + ~'\n'~
2. file size (as string) + ~'\n'~
3. file body

The file name and file size strings must end with a newline ~\n~
character and the file body has no delimiter.

Subsequent files may be streamed by repeating this pattern.  For
examples see:

- [[file:test_boost_custard_write.cpp]] :: First argument is a tar file (~.tar~, ~.tar.gz~ or ~.tar.bz2~) to write and subsequent arguments give files to archive.

- [[file:test_boost_custard_read.cpp]] :: Single argument is a tar file (~.tar~, ~.tar.gz~ or ~.tar.bz2~) to read.  File names and sizes are printed and archive files are written.

Additional tar metadata is set automatically by *custard* and not
currently configurable.


* Also

*custard* also includes 

- [[file:pigenc.hpp]] :: support for Python Numpy file codec

Example and test:

- [[file:test_pigenc.cpp]] :: run with no arguments, creates ~test_pigenc.npy~

* tar + npy = 💕

#+begin_src python
import io, numpy, tarfile
t = tarfile.open("npy.tar")
a = io.BytesIO()
a.write(t.extractfile('bar.npy').read())
arr = numpy.load(a)
#+end_src

* License

*custard* is free software and may be used under the terms described in
the file [[file:COPYING][COPYING]].  


* Todo

- [ ] proper build/test
