#+TITLE: Wire Cell Toolkit Python

* What's here.

This package holds some Python modules that support Wire Cell Toolkit.  Currently this is a stand-alone package that does not depend directly on the C++ packages.  

Some of the main functionality is provides is converters and generators of major WCT input data files including:

- field response functions
- wire geometry

* Installation

This package is somewhat experts only.  It mostly installs in the
"usual Python way", but some packages are more easily provided as system packages rather than via pip.

#+BEGIN_EXAMPLE
  $ sudo apt install python3-vtk7 python3-numpy python3-matplotlib
  $ python3 -m venv --system-site-packages venv
  $ source venv/bin/activate
  $ python setup.py develop
#+END_EXAMPLE

In the future, when creating fresh shells, one only needs

#+BEGIN_EXAMPLE
  $ source venv/bin/activate
#+END_EXAMPLE

Any =git pull= or editing of the code will be reflected in your environment.

* Command line interfaces

Some functionality is available from the command line, with a command
typically named after the module that provides the CLI.  For example:

#+BEGIN_EXAMPLE
  $ wirecell-sigproc --help
  Usage: wirecell-sigproc [OPTIONS] COMMAND [ARGS]...

    Wire Cell Signal Processing Features

  Options:
    --help  Show this message and exit.

  Commands:
    convert-garfield              Convert an archive of a Garfield fileset...
    plot-garfield-track-response
#+END_EXAMPLE

